# Generated by Django 2.2.3 on 2019-10-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0002_squashed_migrations_step2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsrequest',
            name='distancevp',
            field=models.PositiveIntegerField(blank=True, help_text='Indiquez le nombre total de kilomètres parcourus : Par exemple, vous réalisez 2 trajets de 40 kilomètres aller/retour : déclarez 80 kilomètres parcourus.', null=True, verbose_name='Distance (km)'),
        ),
    ]
