# Generated by Django 2.2.3 on 2019-10-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsuser', '0003_adminlocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='caisses',
            field=models.ManyToManyField(to='caisse.Caisse'),
        ),
    ]
